title: Stat arXiv of the Last Week
author: Emanuele Aliverti
email: aliverti@stat.unipd.it
url: https://emanuelealiverti.github.io
baseurl: /arxiv_rss
description: > # description of the site (multiple lines allowed)
feed:
  posts_limit: 100
permalink: 

favicon:

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
